"""Compatibility module for DAFG runtime.

Provides direct access to DAFG runtime classes and functions when imported as `dfag`.
"""

from dafg import (
    DAFG,
    AgentRouter,
    AgentResponse,
    AgentResponseSchema,
    ApprovalStore,
    Backend,
    BackendRegistry,
    Budget,
    BudgetExceededError,
    CompletionGuard,
    DispatchPlan,
    FailureClassifier,
    FailureKind,
    Field,
    Gate,
    GateEngine,
    GateLedger,
    GateLinter,
    GateResult,
    LintIssue,
    NodeStatus,
    PersonaCompiler,
    PersonaProfile,
    PersonaSwitcher,
    PolicyEngine,
    ResponseValidator,
    Role,
    RoutingBlockedError,
    Schema,
    StateStore,
    StopDecision,
    TaskNode,
    ValidationError,
    extract_json,
    nodes_conflict,
    parse_json_response,
    paths_overlap,
    repair_json,
)

__all__ = [
    "DAFG",
    "AgentRouter",
    "AgentResponse",
    "AgentResponseSchema",
    "ApprovalStore",
    "Backend",
    "BackendRegistry",
    "Budget",
    "BudgetExceededError",
    "CompletionGuard",
    "DispatchPlan",
    "FailureClassifier",
    "FailureKind",
    "Field",
    "Gate",
    "GateEngine",
    "GateLedger",
    "GateLinter",
    "GateResult",
    "LintIssue",
    "NodeStatus",
    "PersonaCompiler",
    "PersonaProfile",
    "PersonaSwitcher",
    "PolicyEngine",
    "ResponseValidator",
    "Role",
    "RoutingBlockedError",
    "Schema",
    "StateStore",
    "StopDecision",
    "TaskNode",
    "ValidationError",
    "extract_json",
    "nodes_conflict",
    "parse_json_response",
    "paths_overlap",
    "repair_json",
]

if __name__ == "__main__":
    import sys
    from dafg.cli import main
    sys.exit(main())
