"""Python-native agent coordination and completion-discipline framework."""

from dafg.gates import (
    ApprovalStore,
    Gate,
    GateEngine,
    GateLedger,
    GateLinter,
    GateResult,
    LintIssue,
)
from dafg.runtime import (
    DAFG,
    AgentResponse,
    Budget,
    BudgetExceededError,
    BypassPolicy,
    BypassTelemetry,
    CriterionEvidence,
    EvidenceType,
    FailureClass,
    InputManifest,
    InterfaceContract,
    NodeStatus,
    OutcomeStatus,
    RevisionDirective,
    Role,
    StateStore,
    TaskNode,
    WaitMetrics,
    nodes_conflict,
    paths_overlap,
)
from dafg.hook import (
    CompletionGuard,
    StopDecision,
)
from dafg.schema import (
    AgentResponseSchema,
    BypassPolicySchema,
    BypassTelemetrySchema,
    CriterionEvidenceSchema,
    EvaluationTrialSchema,
    Field,
    InputManifestSchema,
    InterfaceContractSchema,
    ResponseValidator,
    RevisionDirectiveSchema,
    Schema,
    ValidationError,
    extract_json,
    parse_json_response,
    repair_json,
)

from dafg.persona import (
    AgentRouter,
    Backend,
    BackendRegistry,
    DispatchPlan,
    FailureClassifier,
    FailureKind,
    PersonaCompiler,
    PersonaProfile,
    PersonaSwitcher,
    PolicyEngine,
    RoutingBlockedError,
)

from dafg.adapters import (
    BaseRuntimeAdapter,
    IterativeCLIAdapter,
    ReActStateAdapter,
    ToolDispatchAdapter,
)

from dafg.eval import (
    BenchmarkTask,
    CompletionClaim,
    EvaluationHarness,
    EvaluationMetrics,
    EvaluationTrial,
    StandardOutcome,
    validate_test_fixture_syntax,
)

__version__ = "0.3.0"
__all__ = [
    "ApprovalStore",
    "Gate",
    "GateEngine",
    "GateLedger",
    "GateLinter",
    "GateResult",
    "LintIssue",
    "DAFG",
    "AgentResponse",
    "Budget",
    "BudgetExceededError",
    "BypassPolicy",
    "BypassTelemetry",
    "CriterionEvidence",
    "EvidenceType",
    "FailureClass",
    "InputManifest",
    "InterfaceContract",
    "NodeStatus",
    "OutcomeStatus",
    "RevisionDirective",
    "Role",
    "StateStore",
    "TaskNode",
    "WaitMetrics",
    "nodes_conflict",
    "paths_overlap",
    "CompletionGuard",
    "StopDecision",
    "AgentResponseSchema",
    "BypassPolicySchema",
    "BypassTelemetrySchema",
    "CriterionEvidenceSchema",
    "EvaluationTrialSchema",
    "Field",
    "InputManifestSchema",
    "InterfaceContractSchema",
    "ResponseValidator",
    "RevisionDirectiveSchema",
    "Schema",
    "ValidationError",
    "extract_json",
    "parse_json_response",
    "repair_json",
    "AgentRouter",
    "Backend",
    "BackendRegistry",
    "DispatchPlan",
    "FailureClassifier",
    "FailureKind",
    "PersonaCompiler",
    "PersonaProfile",
    "PersonaSwitcher",
    "PolicyEngine",
    "RoutingBlockedError",
    "BaseRuntimeAdapter",
    "IterativeCLIAdapter",
    "ReActStateAdapter",
    "ToolDispatchAdapter",
    "BenchmarkTask",
    "CompletionClaim",
    "EvaluationHarness",
    "EvaluationMetrics",
    "EvaluationTrial",
    "StandardOutcome",
    "validate_test_fixture_syntax",
]
